version: '3.2'
#no windows não aceita mapear caminho aparentemente, usando volume nomeado ao inves disso.
volumes:
  mongo-data: {}
services:
  client:
    container_name: client
    build: client
    ports:
      - '4200:4200'
    # volumes:
    #   - ./client/src:/usr/client/src
    links:
      - server
  server:
    container_name: server
    build: server
    ports:
      - '3000:3000'
    # volumes:
    #   - ./server:/usr/server
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    user: root
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
